# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "picam-monitoring"
BBFILE_PATTERN_picam-monitoring := "^${LAYERDIR}/"
BBFILE_PRIORITY_picam-monitoring = "9"

LAYERVERSION_picam-monitoring = "1"
LAYERDEPENDS_picam-monitoring = "core"
LAYERSERIES_COMPAT_picam-monitoring = "scarthgap"
