# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "picam"
BBFILE_PATTERN_picam := "^${LAYERDIR}/"
BBFILE_PRIORITY_picam = "8"

LAYERVERSION_picam = "1"
LAYERDEPENDS_picam = "core multimedia-layer"
LAYERSERIES_COMPAT_picam = "scarthgap"
